# Copyright (C) 2023 Frachtwerk GmbH, Leopoldstraße 7C, 76133 Karlsruhe.
#
# This file is part of essencium-backend.
#
# essencium-backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# essencium-backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with essencium-backend. If not, see <http://www.gnu.org/licenses/>.

# this configuration needs to correspond to the Vue.js frontends' vue.config.js devServer.proxy.target configuration!
# otherwise you may experience errors like: Proxy error: Could not proxy request /api/hello from localhost:8080 to http://localhost:8088... (ECONNREFUSED).
server:
  port: 8098

app:
  domain: localhost
  url: http://${app.domain}:8098
  auth:
    jwt:
      access-token-expiration: 86400 # 24 hours
      refresh-token-expiration: 2592000 # 30 days
      issuer: Frachtwerk GmbH
      cleanup-interval: 3600 # 1 hour

swagger:
  base-url: ${app.url}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

  h2:
    console:
      enabled: true
      settings:
        trace: true

mail:
  host: smtp.ethereal.email
  port: 587
  username: ahmed14@ethereal.email
  password: sW8rB7kGBPWUBC32ur

  default-sender:
    name: "Local Debug"
    address: "info@frachtwerk.de"

  smtp:
    auth: true
    start-tls: true

  branding:
    logo: "https://static.frachtwerk.de/frachtwerk_320px.png"
    name: "Essencium"
    url: "http://localhost:8098/"
    primary-color: "#00b5d6"
    text-color: "#ffffff"

  new-user-mail:
    template: "NewUserMessage.ftl"
    reset-link: "setPassword?token="
    subject-key: "mail.new-user.subject"

  reset-token-mail:
    template: "ResetTokenMessage.ftl"
    reset-link: "setPassword?token="
    subject-key: "mail.reset-token.subject"

  contact-mail:
    recipients:
      - info@frachtwerk.de
    template: "ContactMessage.ftl"
    locale: "en"
    subject-prefix-key: "mail.contact.subject.prefix"

  new-login-mail:
    subject-key: mail.new-login.subject
    template: NewLoginMessage.ftl

pom:
  version: 0.0.1-TEST

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    de.frachtwerk: DEBUG
    org.hibernate: WARN
    # de.frachtwerk.essencium.backend.controller.access: TRACE
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE

essencium:
  init:
    roles:
      - name: ADMIN
        description: Administrator
        rights: []
        protected: true
      - name: USER
        description: User
        rights:
          - READ
        protected: true
        default-role: true
    users:
      - first-name: Admin
        last-name: User
        username: devnull@frachtwerk.de
        password: adminAdminAdmin
        roles:
          - ADMIN
          - USER
      - first-name: User
        last-name: User
        username: user@frachtwerk.de
        password: userUserUser
        roles:
          - USER
