# Copyright (C) 2026 Frachtwerk GmbH, Leopoldstraße 7C, 76133 Karlsruhe.
#
# This file is part of essencium-backend.
#
# essencium-backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# essencium-backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with essencium-backend. If not, see <http://www.gnu.org/licenses/>.

# --- Build Stage 1: Maven Build ---
FROM maven:3-eclipse-temurin-26 AS build

WORKDIR /build

COPY pom.xml ./pom.xml
COPY license-header.txt ./license-header.txt
COPY .mvn ./.mvn
COPY essencium-backend ./essencium-backend
COPY essencium-backend-development ./essencium-backend-development
COPY essencium-backend-development-uuid ./essencium-backend-development-uuid

RUN --mount=type=cache,target=/root/.m2 mvn -B install -pl essencium-backend -am -Dmaven.test.skip=true -Dgcf.skip=true -Dgpg.skip

RUN --mount=type=cache,target=/root/.m2 mvn -B clean package -pl essencium-backend-development -Dgcf.skip -Dskip.unit.tests -Dskip.integration.tests

RUN cd essencium-backend-development/target && java -Djarmode=tools -jar *.jar extract --layers --destination ./extracted

# --- Build Stage 2: Minimal Runtime ---
FROM eclipse-temurin:26-jre-alpine-3.24

LABEL maintainer="Frachtwerk GmbH"

ENV TZ=Europe/Berlin

RUN apk --no-cache add curl

RUN adduser -D user

USER user

COPY --from=build /build/essencium-backend-development/target/extracted/dependencies/ ./
COPY --from=build /build/essencium-backend-development/target/extracted/application/ ./

EXPOSE 8098

HEALTHCHECK --interval=60s --timeout=30s --start-period=30s --retries=3 CMD curl --fail --silent localhost:8098/actuator/health | grep UP || exit 1

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar *.jar" ]
