# --- Build Stage 1: Maven Build ---
FROM maven:3-eclipse-temurin-26 AS build

WORKDIR /build

COPY pom.xml ./pom.xml
COPY license-header.txt ./license-header.txt
COPY .mvn ./.mvn
COPY essencium-backend ./essencium-backend
COPY essencium-backend-development ./essencium-backend-development
COPY essencium-backend-development-uuid ./essencium-backend-development-uuid

RUN --mount=type=cache,target=/root/.m2 mvn -B install -pl essencium-backend -am -Dmaven.test.skip=true -Dgcf.skip=true -Dgpg.skip

RUN --mount=type=cache,target=/root/.m2 mvn -B clean package -pl essencium-backend-development -Dgcf.skip -Dskip.unit.tests -Dskip.integration.tests

RUN cd essencium-backend-development/target && java -Djarmode=tools -jar *.jar extract --layers --destination ./extracted

# --- Build Stage 2: Minimal Runtime ---
FROM eclipse-temurin:26-jre-alpine-3.23

LABEL maintainer="Frachtwerk GmbH"

ENV TZ=Europe/Berlin

RUN apk --no-cache add curl

RUN adduser -D user

USER user

# Kopiere extrahierte Layer aus dem Build-Container
COPY --from=build /build/essencium-backend-development/target/extracted/dependencies/ ./
COPY --from=build /build/essencium-backend-development/target/extracted/spring-boot-loader/ ./
COPY --from=build /build/essencium-backend-development/target/extracted/snapshot-dependencies/ ./
COPY --from=build /build/essencium-backend-development/target/extracted/application/ ./

EXPOSE 8098

HEALTHCHECK --interval=60s --timeout=30s --start-period=30s --retries=3 CMD curl --fail --silent localhost:8098/actuator/health | grep UP || exit 1

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar *.jar" ]
