# Copyright (C) 2026 Frachtwerk GmbH, Leopoldstraße 7C, 76133 Karlsruhe.
#
# This file is part of essencium-backend.
#
# essencium-backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# essencium-backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with essencium-backend. If not, see <http://www.gnu.org/licenses/>.

name: Essencium CI - Dev

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!main'
      - '!experimental'
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

jobs:
  compile-main:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          cache: 'maven'
      - run: mvn compile -pl essencium-backend
      - uses: actions/upload-artifact@v7
        if: success()
        with:
          name: essencium-backend
          retention-days: 1
          path: "./essencium-backend/target/*"

  unit-tests:
    needs: compile-main
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          cache: 'maven'
      - run: mvn test -pl essencium-backend -Dskip.integration.tests -Dgpg.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: unit-tests-jacoco
          path: essencium-backend/target/jacoco.exec
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: unit-test-reports
          path: essencium-backend/target/surefire-reports/
          if-no-files-found: warn

  integration-tests:
    needs: compile-main
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          cache: 'maven'
      - run: mvn verify -pl essencium-backend -Dskip.unit.tests -Dmaven.source.skip=true -Dgpg.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: integration-tests-jacoco
          path: essencium-backend/target/jacoco-it.exec
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: integration-test-reports
          path: essencium-backend/target/failsafe-reports/
          if-no-files-found: warn

  merge-jacoco-report:
    name: Jacoco Merge Results
    needs:
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          cache: 'maven'
      - uses: actions/download-artifact@v8
        with:
          name: integration-tests-jacoco
          path: essencium-backend/target/
      - uses: actions/download-artifact@v8
        with:
          name: unit-tests-jacoco
          path: essencium-backend/target/
      - name: merge results
        run: mvn jacoco:merge package jacoco:report -pl essencium-backend -DskipTests=true -Dskip.unit.tests -Dskip.integration.tests -Dmaven.source.skip=true -Dgpg.skip=true
      - name: Upload jacoco coverage despite the check result
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: coverage-results-report
          path: essencium-backend/target/site/jacoco/
          if-no-files-found: error

  test-demo-application:
    name: Test Demo Application
    needs:
      - compile-main
      - unit-tests
      - integration-tests
      - merge-jacoco-report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          cache: 'maven'
      - uses: actions/download-artifact@v8
        with:
          name: essencium-backend
          path: essencium-backend/target/
      - run: mvn install -pl essencium-backend -am -DskipTests=true -Dskip.unit.tests -Dskip.integration.tests -Dmaven.source.skip -Dgpg.skip=true
      - run: mvn test -pl essencium-backend-development

  test-demo-application-uuid:
    name: Test Demo Application (UUID-based)
    needs:
      - compile-main
      - unit-tests
      - integration-tests
      - merge-jacoco-report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          cache: 'maven'
      - uses: actions/download-artifact@v8
        with:
          name: essencium-backend
          path: essencium-backend/target/
      - run: mvn install -pl essencium-backend -am -DskipTests=true -Dskip.unit.tests -Dskip.integration.tests -Dmaven.source.skip -Dgpg.skip=true
      - run: mvn test -pl essencium-backend-development-uuid

  sonarcloud-analysis:
    name: SonarCloud analysis
    needs:
      - merge-jacoco-report
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v7
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        if: ${{ env.SONAR_TOKEN != '' }}
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          cache: 'maven'
      - uses: actions/download-artifact@v8
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          name: coverage-results-report
          path: essencium-backend/target/site/jacoco/
      - uses: actions/download-artifact@v8
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          name: unit-test-reports
          path: essencium-backend/target/surefire-reports/
      - uses: actions/download-artifact@v8
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          name: integration-test-reports
          path: essencium-backend/target/failsafe-reports/
      - name: Analyze with SonarCloud
        if: ${{ env.SONAR_TOKEN != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        run: >
          mvn sonar:sonar -pl essencium-backend -am -DskipTests=true -Dskip.unit.tests -Dskip.integration.tests -Dmaven.source.skip=true -Dgpg.skip=true
          -Dsonar.projectKey=Frachtwerk_essencium-backend -Dsonar.organization=frachtwerk -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          -Dsonar.junit.reportPaths=target/surefire-reports,target/failsafe-reports -Dsonar.tests=src/test,src/testIntegration

