# Copyright (C) 2026 Frachtwerk GmbH, Leopoldstraße 7C, 76133 Karlsruhe.
#
# This file is part of essencium-backend.
#
# essencium-backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# essencium-backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with essencium-backend. If not, see <http://www.gnu.org/licenses/>.

name: Essencium CI - Dev

on:
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: mvn test -pl essencium-backend -Dskip.integration.tests
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: unit-tests-jacoco
          path: essencium-backend/target/jacoco.exec
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: unit-test-reports
          path: essencium-backend/target/surefire-reports/
          if-no-files-found: warn

  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: mvn verify -pl essencium-backend -Dskip.unit.tests -Dmaven.source.skip=true
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: integration-tests-jacoco
          path: essencium-backend/target/jacoco-it.exec
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: integration-test-reports
          path: essencium-backend/target/failsafe-reports/
          if-no-files-found: warn

  merge-jacoco-report:
    name: Jacoco Merge Results
    needs:
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - uses: actions/download-artifact@v8
        with:
          name: integration-tests-jacoco
          path: essencium-backend/target/
      - uses: actions/download-artifact@v8
        with:
          name: unit-tests-jacoco
          path: essencium-backend/target/
      - name: merge results
        run: mvn jacoco:merge package jacoco:report -pl essencium-backend -DskipTests=true -Dskip.unit.tests -Dskip.integration.tests -Dmaven.source.skip=true
      - name: Upload jacoco coverage despite the check result
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: coverage-results-report
          path: essencium-backend/target/site/jacoco/
          if-no-files-found: error

  test-demo-application:
    name: Test Demo Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: mvn install -pl essencium-backend -am -DskipTests=true -Dskip.unit.tests -Dskip.integration.tests -Dmaven.source.skip
      - run: mvn test -pl essencium-backend-development

  test-demo-application-uuid:
    name: Test Demo Application (UUID-based)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: mvn install -pl essencium-backend -am -DskipTests=true -Dskip.unit.tests -Dskip.integration.tests -Dmaven.source.skip
      - run: mvn test -pl essencium-backend-development-uuid

  sonarcloud-analysis:
    name: SonarCloud analysis
    needs:
      - merge-jacoco-report
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v7
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - uses: actions/download-artifact@v8
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          name: coverage-results-report
          path: essencium-backend/target/site/jacoco/
      - uses: actions/download-artifact@v8
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          name: unit-test-reports
          path: essencium-backend/target/surefire-reports/
      - uses: actions/download-artifact@v8
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          name: integration-test-reports
          path: essencium-backend/target/failsafe-reports/
      - name: Analyze with SonarCloud
        if: ${{ env.SONAR_TOKEN != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        run: >
          mvn test-compile sonar:sonar -pl essencium-backend -Dmaven.source.skip=true
          -Dsonar.projectKey=Frachtwerk_essencium-backend -Dsonar.organization=frachtwerk -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          -Dsonar.junit.reportPaths=target/surefire-reports,target/failsafe-reports -Dsonar.tests=src/test,src/testIntegration

